name: Bug report
description: Create a report to help us improve
title: '[BUG]: '
labels: 'bug'
assignees: 
  - Bonislolz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
  - type: dropdown
    id: pkg_version
    attributes:
      label: dictrack version
      description: What version of dictrack are you using?
      options:
        - 2.x (latest)
        - 1.x
        - 0.x
      default: 0
    validations:
      required: true
  - type: dropdown
    id: py_version
    attributes:
      label: Python version
      description: What version of Python are you using?
      options:
        - 3.7+
        - 2.7
    validations:
      required: true
