name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: "bug"
assignees: 
  - Bonislolz
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
