name: Feature request
description: Suggest an idea for this project
title: '[FEATURE]: '
labels: 'enhancement'
assignees: 
  - Bonislolz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        We also welcome direct PRs to speed up the development process :D
  - type: input
    attributes:
      label: Feature Description
      description: How can we get in touch with you if we need more idea?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    attributes:
      label: What happened?
      description: Please provide a detailed description of the feature you want to suggest.
      placeholder: Describe your idea here!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Benefits
      description: How will this feature improve the project or your workflow?
      placeholder: Share how this feature can help!
    validations:
      required: true
